[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "RTA Dubai API"
authors = [{name = "Patrick", email = "rakexpatriate@gmail.com"}]
dynamic = ["version", "description"]
